repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.96.1
    hooks:
      - id: terraform_fmt
      - id: terraform_validate
      - id: checkov
        args:
          - "--quiet"
          - "--compact"
          - "--skip-check"
          - "CKV_GCP_62,CKV_GCP_125,CKV_GCP_45,CKV_GCP_38,CKV_GCP_81,CKV_GCP_6,CKV_GCP_79,CKV_GCP_109"
      - id: terraform_docs
        args:
          - "--args=--sort-by required"
